platform :ios, '6.0'
pod 'AFNetworking'
pod 'AFTumblrAPIClient', '~> 0.0.4'
pod 'AFKissXMLRequestOperation'
pod 'FormatterKit','1.1.1'
pod 'DWTagList'
pod 'AFStatHatClient'
pod 'SVProgressHUD'
pod 'FlatUIKit'
pod 'SGSStaggeredFlowLayout', :git => 'https://github.com/pj4533/SGSStaggeredFlowLayout'
pod 'TMCache'
pod 'FormatterKit'
pod 'AFRedditAPIClient'