fastlane_version "1.49.0"

default_platform :ios


desc "Submit a new Release Candidate Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :appstore do |options|

  sigh(
    output_path: ".sigh"
  )

  gym(
    scheme: "OpenPics",
    configuration: "Release",
    output_directory: ".gym"      
  )
  
  pilot(
    skip_submission: true
  )

  add_git_tag(
    grouping: `cd ..;agvtool mvers -terse1`.strip,
    build_number: `cd ..;agvtool vers -terse`.strip
  )

  increment_build_number(
    xcodeproj: "OpenPics.xcodeproj"
  )
  
  commit_version_bump(
    xcodeproj: "OpenPics.xcodeproj"
  )

  push_to_git_remote
end
